FROM python:3.11-bullseye
WORKDIR /app
COPY requirements.txt .
RUN --mount=type=cache,target=/root/.cache/pip pip install -r requirements.txt
# Additional package for PDF generation
RUN --mount=type=cache,target=/root/.cache/pip pip install reportlab
COPY . .
EXPOSE 4001
CMD ["uvicorn", "main:app", "--host", "0.0.0.0", "--port", "4001"]
