// AlertFeed.jsx — Phase 5A
// Shows engagement alerts from the backend.
// New in 5A:
//   • "AI" badge on suggestions generated by HuggingFace (payload.suggestionAI)
//   • Expand/collapse full suggestion on click
//   • Richer type-to-colour mapping including CONFUSION_SPIKE
//   • Relative timestamp

import { useState } from 'react';

const TYPE_CONFIG = {
  SILENT_PARTICIPANTS:    { label: 'Silent',    bg: 'bg-blue-500/15',   text: 'text-blue-300',   border: 'border-blue-500/30'   },
  PARTICIPATION_IMBALANCE:{ label: 'Imbalance', bg: 'bg-yellow-500/15', text: 'text-yellow-300', border: 'border-yellow-500/30' },
  CONFUSION_SPIKE:        { label: 'Confused',  bg: 'bg-rose-500/15',   text: 'text-rose-300',   border: 'border-rose-500/30'   },
  ENGAGEMENT_DROP:        { label: 'Drop',      bg: 'bg-orange-500/15', text: 'text-orange-300', border: 'border-orange-500/30' },
  DEFAULT:                { label: 'Alert',     bg: 'bg-slate-500/15',  text: 'text-slate-300',  border: 'border-slate-500/30'  },
};

function relTime(ts) {
  if (!ts) return '';
  const diff = Math.floor((Date.now() - ts) / 1000);
  if (diff < 60)  return `${diff}s ago`;
  if (diff < 3600) return `${Math.floor(diff / 60)}m ago`;
  return `${Math.floor(diff / 3600)}h ago`;
}

function AlertCard({ alert }) {
  const [expanded, setExpanded] = useState(false);
  const cfg = TYPE_CONFIG[alert.type] || TYPE_CONFIG.DEFAULT;

  return (
    <div
      className={`rounded-xl border ${cfg.border} ${cfg.bg} p-3 cursor-pointer select-none`}
      onClick={() => setExpanded((e) => !e)}
    >
      {/* Header row */}
      <div className="flex items-start justify-between gap-2">
        <div className="flex items-center gap-2">
          <span className={`text-xs font-semibold px-2 py-0.5 rounded-full ${cfg.bg} ${cfg.text} border ${cfg.border}`}>
            {cfg.label}
          </span>
          <p className="text-sm text-slate-200 leading-snug">{alert.message}</p>
        </div>
        <div className="flex items-center gap-1.5 shrink-0">
          <span className="text-xs text-slate-500">{relTime(alert.receivedAt)}</span>
          <span className="text-slate-500 text-xs">{expanded ? '▲' : '▼'}</span>
        </div>
      </div>

      {/* Suggestion — shown when expanded */}
      {expanded && alert.suggestion && (
        <div className="mt-2 pt-2 border-t border-white/5">
          <div className="flex items-center gap-1.5 mb-1">
            <span className="text-xs text-slate-400">Suggested action</span>
            {alert.suggestionAI && (
              <span className="text-xs px-1.5 py-0.5 rounded bg-violet-500/20 text-violet-300 border border-violet-500/30">
                AI
              </span>
            )}
            {!alert.suggestionAI && (
              <span className="text-xs px-1.5 py-0.5 rounded bg-slate-500/20 text-slate-400 border border-slate-500/20">
                suggested
              </span>
            )}
          </div>
          <p className="text-sm text-white leading-relaxed">{alert.suggestion}</p>
        </div>
      )}
    </div>
  );
}

export default function AlertFeed({ alerts }) {
  if (!alerts.length) {
    return (
      <div className="flex flex-col items-center justify-center h-32 text-slate-500 gap-1">
        <span className="text-2xl">📬</span>
        <p className="text-xs">No alerts yet. Agents are watching…</p>
      </div>
    );
  }

  return (
    <div className="flex flex-col gap-2 overflow-y-auto max-h-[420px] pr-1">
      {alerts.map((a, i) => (
        <AlertCard key={`${a.type}-${a.receivedAt || i}`} alert={a} />
      ))}
    </div>
  );
}
