-- Phase 10: engagement_alerts table
-- Stores actionable alerts generated by the SignalAggregator

create table if not exists engagement_alerts (
  id           uuid primary key default gen_random_uuid(),
  session_id   uuid references sessions(id) on delete cascade not null,
  student_id   uuid references session_students(id) on delete cascade not null,
  alert_type   text not null check (alert_type in ('watch', 'intervene')),
  message      text not null,
  fused_score  numeric(5,2),
  created_at   timestamptz default now()
);

create index if not exists idx_alerts_session on engagement_alerts(session_id, created_at desc);
create index if not exists idx_alerts_student on engagement_alerts(student_id, created_at desc);

-- Row Level Security
alter table engagement_alerts enable row level security;
create policy "Teacher can view session alerts"
  on engagement_alerts for select
  using (true);  -- scope to authenticated teacher in Phase 11 auth
